### ISSUE TITLE
Doesn't run on Ubuntu 22.04

### ISSUE THREAD

**Issue by cre8tions** [satoverse/satoxcoin#5]
### Describe the issue
Running on Ubuntu 22.04 fails, both daemon and QT app

### Screenshots.
```
# satoxcoind
satoxcoind: malloc.c:2617: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Aborted (core dumped)
```

### What version of satoxare you using?
_Satoxcoin version v2.1.0.0-g25a2dbf41_

### Machine specs:
- OS: _Ubuntu 22.04.4 LTS x86_64 / Linux 6.5.0-25-generic_
- CPU: _24 x AMD Ryzen 9 7900X 12-Core Processor_
- RAM: _63425 MiB_
- Disk size: _3.6 TiB_
- Disk Type: _SDD_

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by satoverse** [comment]
Hi you can use this instructions to get it running on Ubuntu 22.04 

[https://docs.satoverse.io/docs/support-satox/install-wallet-for-ubuntu-22.04](https://docs.satoverse.io/docs/support-satox/install-wallet-for-ubuntu-22.04)
